
server:
  port: 8080

spring:
  application:
    name: microservice-provider-user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springproject?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.microservice.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka

