#服务名称
server:
  port: 5001
# 应用名称
spring:
        application:
           name:microservice-consumer-movie
####\u6570\u636E\u5E93\u7684\u8FDE\u63A5\u914D\u7F6E
  spring:
    datasource:
      url:jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username:root
      password:root
      driver-class-name:com.mysql.jdbc.Driver

      tomcat.max-active=20
      dbcp2.max-idle=8
      dbcp2.min-idle=8
      initial-size=10
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/